language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "lts/*"

jobs:
  include:
    - stage: npm release
      node_js: "lts/*"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_API_KEY
        on:
          tags: true
          branch: master
